name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      # It will check out code this is already written code by someone else we are just using it,use to clone
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 54.210.175.137 # whatever is the ip of the instance
          username: ubuntu
          password: ${{secrets.PRIVATE_SSH_KEY}} #what ever is the ssh private
          port: 22
          script: whoami
